"""empty message

Revision ID: 97505021bc44
Revises: d6c02ccb58f2
Create Date: 2023-12-29 20:48:19.664049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97505021bc44'
down_revision = 'd6c02ccb58f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament__info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_name', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.String(length=15), nullable=False),
    sa.Column('end_date', sa.String(length=15), nullable=False),
    sa.Column('state', sa.CHAR(length=2), nullable=False),
    sa.Column('bid_level', sa.String(length=40), nullable=False),
    sa.Column('in_person', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournament__info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournament__info_bid_level'), ['bid_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournament__info_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournament__info_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournament__info_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournament__info_tournament_name'), ['tournament_name'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_bid_level')
        batch_op.drop_index('ix_user_end_date')
        batch_op.drop_index('ix_user_start_date')
        batch_op.drop_index('ix_user_state')
        batch_op.drop_index('ix_user_tournament_name')

    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tournament_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('start_date', sa.VARCHAR(length=15), nullable=False),
    sa.Column('end_date', sa.VARCHAR(length=15), nullable=False),
    sa.Column('state', sa.CHAR(length=2), nullable=False),
    sa.Column('bid_level', sa.VARCHAR(length=40), nullable=False),
    sa.Column('in_person', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_tournament_name', ['tournament_name'], unique=1)
        batch_op.create_index('ix_user_state', ['state'], unique=False)
        batch_op.create_index('ix_user_start_date', ['start_date'], unique=False)
        batch_op.create_index('ix_user_end_date', ['end_date'], unique=False)
        batch_op.create_index('ix_user_bid_level', ['bid_level'], unique=False)

    with op.batch_alter_table('tournament__info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournament__info_tournament_name'))
        batch_op.drop_index(batch_op.f('ix_tournament__info_state'))
        batch_op.drop_index(batch_op.f('ix_tournament__info_start_date'))
        batch_op.drop_index(batch_op.f('ix_tournament__info_end_date'))
        batch_op.drop_index(batch_op.f('ix_tournament__info_bid_level'))

    op.drop_table('tournament__info')
    # ### end Alembic commands ###
