"""empty message

Revision ID: d6c02ccb58f2
Revises: 
Create Date: 2023-12-29 20:42:15.125144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c02ccb58f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_name', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.String(length=15), nullable=False),
    sa.Column('end_date', sa.String(length=15), nullable=False),
    sa.Column('state', sa.CHAR(length=2), nullable=False),
    sa.Column('bid_level', sa.String(length=40), nullable=False),
    sa.Column('in_person', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_bid_level'), ['bid_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_tournament_name'), ['tournament_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_tournament_name'))
        batch_op.drop_index(batch_op.f('ix_user_state'))
        batch_op.drop_index(batch_op.f('ix_user_start_date'))
        batch_op.drop_index(batch_op.f('ix_user_end_date'))
        batch_op.drop_index(batch_op.f('ix_user_bid_level'))

    op.drop_table('user')
    # ### end Alembic commands ###
